import React from "react"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Download, Edit, Globe } from "lucide-react"

interface ReportFooterProps {
  id: string
}

export default function ReportFooter({ id }: ReportFooterProps) {
  return (
    <Card className="p-6 border shadow-sm sticky bottom-4 mt-8 bg-background/95 backdrop-blur-sm">
      <div className="flex flex-wrap gap-4 justify-center md:justify-between">
        <div className="text-sm text-muted-foreground">
          Report generated by Startup Validator
        </div>
        
        <div className="flex flex-wrap gap-2">
          <Button variant="outline" size="sm" className="flex items-center gap-1">
            <Download className="h-4 w-4" />
            <span>Download PDF</span>
          </Button>
          
          <Button variant="outline" size="sm" className="flex items-center gap-1">
            <Edit className="h-4 w-4" />
            <span>Refine & Rescore</span>
          </Button>
          
          <Button size="sm" className="flex items-center gap-1">
            <Globe className="h-4 w-4" />
            <span>Publish Report</span>
          </Button>
        </div>
      </div>
    </Card>
  )
} 